import { contentBundleSchema } from '@/content/schemas';

const candidateSeed = {
  schemaVersion: 1,
  user: {
    id: 'user-neo-demo',
    displayName: 'Neo',
    streakDays: 4,
    dailyGoalMinutes: 10,
    reminderLocalTime: '19:30',
    startingLevelChoice: 'a-little',
  },
  course: {
    id: 'course-isi-zulu',
    languageCode: 'zu',
    languageName: 'isiZulu',
    title: 'Everyday isiZulu',
  },
  unit: {
    id: 'unit-greetings',
    courseId: 'course-isi-zulu',
    title: 'Greetings',
    order: 1,
  },
  lesson: {
    id: 'lesson-introduce-yourself',
    unitId: 'unit-greetings',
    title: 'Introduce yourself',
    durationMinutes: 12,
    level: 'Beginner',
    activities: [
      {
        id: 'activity-introduce-listen',
        kind: 'listen',
        order: 1,
        required: true,
        prompt: 'Sawubona! Igama lami nguNeo.',
        translation: 'Hello! My name is Neo.',
        audioAssetId: 'audio-neo-introduction',
      },
      {
        id: 'activity-introduce-phrase-builder',
        kind: 'phrase-builder',
        order: 2,
        required: true,
        prompt: 'Hello, my name is Neo.',
        answer: 'Sawubona. Igama lami nguNeo.',
        audioAssetId: 'audio-neo-introduction',
      },
      {
        id: 'activity-introduce-picture-match',
        kind: 'picture-match',
        order: 3,
        required: true,
        prompt: 'Tap the picture for:',
        answer: 'amanzi',
        choices: [
          { id: 'picture-water', label: 'Water', correct: true, imageKey: 'water' },
          { id: 'picture-bread', label: 'Bread', correct: false, imageKey: 'bread' },
          { id: 'picture-house', label: 'House', correct: false, imageKey: 'house' },
          { id: 'picture-family', label: 'Family', correct: false, imageKey: 'family' },
        ],
      },
      {
        id: 'activity-introduce-conversation',
        kind: 'conversation',
        order: 4,
        required: true,
        prompt: 'Sawubona! Unjani namhlanje?',
        translation: 'Hello! How are you today?',
        choices: [
          { id: 'reply-social', label: 'Kahle, ngiyabonga. Wena?', correct: true },
          { id: 'reply-name', label: 'Igama lami nguNeo.', correct: false },
          { id: 'reply-farewell', label: 'Hamba kahle.', correct: false },
        ],
      },
      {
        id: 'activity-introduce-comprehension',
        kind: 'comprehension',
        order: 5,
        required: true,
        prompt: 'What did Lerato say?',
        answer: 'I’m Lerato.',
        audioAssetId: 'audio-lerato-introduction',
        choices: [
          { id: 'meaning-lerato', label: 'I’m Lerato.', correct: true },
          { id: 'meaning-leaving', label: 'I’m leaving.', correct: false },
          { id: 'meaning-studying', label: 'I’m studying.', correct: false },
        ],
      },
      {
        id: 'activity-introduce-dictation',
        kind: 'dictation',
        order: 6,
        required: true,
        prompt: 'Listen and type what you hear.',
        answer: 'Ngiyaphila, ngiyabonga.',
        audioAssetId: 'audio-neo-wellbeing',
      },
      {
        id: 'activity-introduce-pronunciation',
        kind: 'pronunciation',
        order: 7,
        required: true,
        prompt: 'Tap each part to practise.',
        answer: 'Sawubona. Igama lami nguNeo.',
        audioAssetId: 'audio-neo-introduction',
      },
      {
        id: 'activity-introduce-speak',
        kind: 'speak',
        order: 8,
        required: true,
        prompt: 'Say the phrase',
        answer: 'Sawubona. Igama lami nguNeo.',
      },
    ],
  },
  phrases: ['Sawubona', 'Igama lami nguNeo', 'Ngiyabonga'],
  storyCharacter: 'Lerato',
  featuredPracticeTitle: 'At the taxi rank',
} as const;

export const buaSeedContent = contentBundleSchema.parse(candidateSeed);
